### ISSUE TITLE
Remove included db.json and use the one from breviter

### ISSUE THREAD

**Issue by ribose-jeffreylau** [geolexica/breviter-compare#4]

**Comment by ronaldtse** [comment]
@HassanAkbar can you help update the code so that we do not use db.json, but instead, calculate the db.json file directly using the corresponding code from Breviter? The ISO/TC 211 concept database is provided in this repo as a submodule.

**Comment by HassanAkbar** [comment]
@ronaldtse The generation of the `db.json` file requires the `model.json` file and `vocab.json` file from the breviter repo. Should I copy both of those files in the `breviter-compare` repo or would you suggest a different approach?

**Comment by ronaldtse** [comment]
@HassanAkbar this current repo can directly submodule or pull from the Breviter repository.

**Comment by HassanAkbar** [comment]
@ronaldtse I’ve added breviter as a submodule to this repo.

Do I need to extract the code that generated the `db.json` file or can I run the `yarn compute` in the breviter repo (which is a submodule in here) and then copy the freshly generated `db.json` file?

**Comment by ronaldtse** [comment]
We just need to run `yarn compute`, of course. Thanks!
